# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_id',
            field=models.IntegerField(),
        ),
    ]
